spring:
  application:
    name: business-service

  data:
    mongodb:
      host: 127.0.0.1
server:
  port: 8086

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.web: TRACE